### ISSUE TITLE
Whats the difference to 'pwd'

### ISSUE THREAD

**Issue by michaelzoidl** [sindresorhus/self-path#1]
I see the issue you want to resolve with this module, but whats the difference to the command `pwd` (or `%cd%` in windows)?

**Comment by mastilver** [comment]
This will always print the same path, whatever your current directory is

Let's say your current directory is: `~/foobar`
- `pwd` -> `/Users/sindresorhus/foobar`
- `self-path` -> `/Users/sindresorhus/n/lib/node_modules/self-path`

I can see it being useful when you have a buggy setup:
For example on windows it happens frequently that `npm` is installed twice, using `self-path` you can check where `npm` is installing modules globally
